-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop existing tables with CASCADE to handle dependencies
DROP TABLE IF EXISTS form_responses CASCADE;
DROP TABLE IF EXISTS responses CASCADE;
DROP TABLE IF EXISTS forms CASCADE;

-- Create forms table
CREATE TABLE forms (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id uuid NOT NULL,
    title text NOT NULL,
    description text,
    fields jsonb NOT NULL,
    theme text DEFAULT 'default',
    created_at timestamptz DEFAULT now(),
    updated_at timestamptz DEFAULT now()
);

-- Create form_responses table
CREATE TABLE form_responses (
    id uuid DEFAULT uuid_generate_v4() PRIMARY KEY,
    form_id bigint NOT NULL,
    response_data jsonb NOT NULL,
    created_at timestamptz DEFAULT now(),
    CONSTRAINT fk_form
        FOREIGN KEY (form_id)
        REFERENCES forms(id)
        ON DELETE CASCADE
);

-- Grant permissions
GRANT ALL ON forms TO authenticated;
GRANT ALL ON forms TO service_role;
GRANT ALL ON form_responses TO authenticated;
GRANT ALL ON form_responses TO service_role;

-- Create indexes for faster lookups
CREATE INDEX idx_forms_user_id ON forms(user_id);
CREATE INDEX idx_form_responses_form_id ON form_responses(form_id); 